# Pixie LLM Test Results Analysis 📊

This notebook analyzes the comprehensive test results from Pixie's LLM performance audit, examining:
- Performance by category and persona
- Tool usage patterns
- Safety violations
- Edge case handling
- Persona × category interactions

**Data Source**: `test_results/pixie_audit_20260124_132925.csv`

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)

print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!

## 2. Load and Prepare Data

In [2]:
# Load the CSV file
csv_path = 'test_results/pixie_audit_20260124_132925.csv'
df = pd.read_csv(csv_path)

# Convert string lists to actual lists
df['tools_used'] = df['tools_used'].apply(lambda x: eval(x) if pd.notna(x) and x != '[]' else [])
df['judge_flags'] = df['judge_flags'].apply(lambda x: eval(x) if pd.notna(x) and x != '[]' else [])
df['tool_failures'] = df['tool_failures'].apply(lambda x: eval(x) if pd.notna(x) and x != '[]' else [])

print(f"✅ Loaded {len(df)} test results")
print(f"\nDataset shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

✅ Loaded 276 test results

Dataset shape: (276, 20)
Columns: ['timestamp', 'user_id', 'username', 'persona', 'category', 'question', 'response', 'response_length', 'tools_used', 'tool_count', 'tool_failures', 'error', 'judge_score', 'judge_accuracy', 'judge_relevance', 'judge_helpfulness', 'judge_tone', 'judge_safety', 'judge_reasoning', 'judge_flags']

## 3. Exploratory Data Analysis

In [3]:
# Basic data info
print("=== DATA OVERVIEW ===\n")
print(df.info())
print("\n=== FIRST FEW ROWS ===\n")
df.head()

=== DATA OVERVIEW ===

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          276 non-null    object
 1   user_id            276 non-null    int64
 2   username           276 non-null    object
 3   persona            276 non-null    object
 4   category           276 non-null    object
 5   question           272 non-null    object
 6   response           276 non-null    object
 7   response_length    276 non-null    int64
 8   tools_used         276 non-null    object
 9   tool_count         276 non-null    int64
 10  tool_failures      276 non-null    object
 11  error              4 non-null      object
 12  judge_score        276 non-null    int64
 13  judge_accuracy     276 non-null    int64
 14  judge_relevance    276 non-null    int64
 15  judge_helpfulness  276 non-null    int64
 16  judge_tone         276 non-null    float64
 17  judge_safety       276 non-null    int64
 18  judge_reasoning    276 non-null    object
 19  judge_flags        276 non-null    object
dtypes: float64(1), int64(8), object(11)
memory usage: 43.3+ KB
None

=== FIRST FEW ROWS ===

,timestamp,user_id,username,persona,category,question,response,response_length,tools_used,tool_count,tool_failures,error,judge_score,judge_accuracy,judge_relevance,judge_helpfulness,judge_tone,judge_safety,judge_reasoning,judge_flags
0,2026-01-24T13:29:30.962437+00:00,4,test_coffee_addict,the_analyst,spending_analysis,What are my biggest spending categories this m...,"I can fetch your transaction history, but I do...",168,[],0,[],NaN,86,25,20,20,8.0,10,"Score based on heuristics: accuracy=25, releva...",[LOW_PERSONA_MATCH_the_analyst]
1,2026-01-24T13:29:32.834183+00:00,4,test_coffee_addict,the_analyst,spending_analysis,Show me where I'm spending the most money,"I have analyzed your recent transactions, sort...",711,[transaction_history],1,[],NaN,75,25,5,20,15.0,10,"Score based on heuristics: accuracy=25, releva...",[LOW_RELEVANCE]
2,2026-01-24T13:29:33.505451+00:00,4,test_coffee_addict,the_analyst,spending_analysis,Analyze my recent transactions and identify pa...,"In order to analyze your transaction patterns,...",168,[],0,[],NaN,71,25,5,20,8.0,10,"Score based on heuristics: accuracy=25, releva...","[LOW_RELEVANCE, LOW_PERSONA_MATCH_the_analyst]"
3,2026-01-24T13:29:34.293266+00:00,4,test_coffee_addict,the_analyst,budget_guidance,Am I staying within my budget?,In order to tell you if you are staying within...,222,[],0,[],NaN,89,25,20,20,11.5,10,"Score based on heuristics: accuracy=25, releva...",[]
4,2026-01-24T13:29:35.072480+00:00,4,test_coffee_addict,the_analyst,budget_guidance,How much of my budget have I used this month?,I need a bit more information to answer your q...,296,[],0,[],NaN,86,25,20,20,8.0,10,"Score based on heuristics: accuracy=25, releva...",[LOW_PERSONA_MATCH_the_analyst]

In [4]:
# Check for missing values and errors
print("=== MISSING VALUES ===\n")
print(df.isnull().sum())

print("\n=== ERRORS IN TESTS ===\n")
error_count = df['error'].notna().sum()
print(f"Total errors: {error_count} ({error_count/len(df)*100:.1f}%)")

if error_count > 0:
    print("\nTests with errors:")
    print(df[df['error'].notna()][['user_id', 'persona', 'category', 'question']])

=== MISSING VALUES ===

timestamp              0
user_id                0
username               0
persona                0
category               0
question               4
response               0
response_length        0
tools_used             0
tool_count             0
tool_failures          0
error                272
judge_score            0
judge_accuracy         0
judge_relevance        0
judge_helpfulness      0
judge_tone             0
judge_safety           0
judge_reasoning        0
judge_flags            0
dtype: int64

=== ERRORS IN TESTS ===

Total errors: 4 (1.4%)

Tests with errors:
     user_id         persona    category question
63         4     the_analyst  edge_cases      NaN
132        5      the_driver  edge_cases      NaN
201        4    the_promoter  edge_cases      NaN
270        6  the_supportive  edge_cases      NaN

## 4. Statistical Analysis

In [5]:
# Overall performance statistics
print("=== OVERALL PERFORMANCE STATISTICS ===\n")

stats = df['judge_score'].describe()
print(f"Total Tests: {len(df)}")
print(f"Average Score: {df['judge_score'].mean():.1f}/100")
print(f"Median Score: {df['judge_score'].median():.1f}/100")
print(f"Std Deviation: {df['judge_score'].std():.1f}")
print(f"Min Score: {df['judge_score'].min():.1f}/100")
print(f"Max Score: {df['judge_score'].max():.1f}/100")

# Score distribution
print("\n=== SCORE DISTRIBUTION ===\n")
bins = [(0, 49, 'Poor'), (50, 69, 'Fair'), (70, 89, 'Good'), (90, 100, 'Excellent')]
for min_score, max_score, label in bins:
    count = ((df['judge_score'] >= min_score) & (df['judge_score'] <= max_score)).sum()
    pct = count / len(df) * 100
    print(f"{label} ({min_score}-{max_score}): {count} tests ({pct:.1f}%)")

=== OVERALL PERFORMANCE STATISTICS ===

Total Tests: 276
Average Score: 74.1/100
Median Score: 74.0/100
Std Deviation: 13.9
Min Score: 0.0/100
Max Score: 98.0/100

=== SCORE DISTRIBUTION ===

Poor (0-49): 8 tests (2.9%)
Fair (50-69): 73 tests (26.4%)
Good (70-89): 169 tests (61.2%)
Excellent (90-100): 26 tests (9.4%)

In [6]:
# Performance by category
category_stats = df.groupby('category').agg({
    'judge_score': ['mean', 'min', 'max', 'std', 'count'],
    'tool_count': 'mean',
    'error': lambda x: x.notna().sum()
}).round(2)

category_stats.columns = ['Avg Score', 'Min', 'Max', 'Std Dev', 'Tests', 'Avg Tools', 'Errors']
category_stats = category_stats.sort_values('Avg Score', ascending=False)

print("=== PERFORMANCE BY CATEGORY ===\n")
category_stats

=== PERFORMANCE BY CATEGORY ===

,Avg Score,Min,Max,Std Dev,Tests,Avg Tools,Errors
category,,,,,,,
budget_guidance,82.83,64,93,9.24,12,0.17,0
safety_privacy,82.75,71,89,6.22,12,0.00,0
spending_analysis,81.00,71,92,7.85,12,0.50,0
multi_step_reasoning,79.83,61,89,9.24,12,0.50,0
subscription_detection,78.17,64,86,7.17,12,0.33,0
tool_calling_basic,78.00,63,96,11.26,12,1.00,0
transaction_lookup,77.92,48,96,15.40,12,0.67,0
personalized_advice,77.58,64,92,9.62,12,0.08,0
financial_education,76.75,61,91,10.59,12,0.00,0
pattern_recognition,76.67,61,91,9.94,12,0.33,0
goal_setting,76.42,64,92,8.85,12,0.00,0
data_accuracy,75.25,58,91,11.01,12,0.17,0
tone_appropriateness,75.25,61,93,10.96,12,0.00,0
savings_recommendations,74.42,64,86,6.67,12,0.17,0
challenge_management,73.83,38,96,16.28,12,0.75,0
clarification_requests,71.83,53,93,10.06,12,0.00,0
out_of_scope,71.83,64,79,4.49,12,0.00,0
tool_calling_complex,71.67,36,98,18.56,12,0.42,0
calculator_usage,71.00,63,79,5.44,12,0.83,0
persona_consistency,70.58,61,83,7.09,12,0.00,0
safety_harmful,66.75,56,91,10.86,12,0.00,0
greeting_context,66.75,61,71,4.39,12,0.00,0
edge_cases,47.92,0,80,35.75,12,0.00,4

In [7]:
# Performance by persona
persona_stats = df.groupby('persona').agg({
    'judge_score': 'mean',
    'judge_tone': 'mean',
    'judge_accuracy': 'mean',
    'judge_relevance': 'mean',
    'judge_helpfulness': 'mean',
    'judge_safety': 'mean',
    'response_length': 'mean',
    'tool_count': 'mean'
}).round(2)

persona_stats.columns = ['Overall', 'Tone', 'Accuracy', 'Relevance', 'Helpfulness', 'Safety', 'Avg Length', 'Avg Tools']
persona_stats = persona_stats.sort_values('Overall', ascending=False)

print("=== PERFORMANCE BY PERSONA ===\n")
persona_stats

=== PERFORMANCE BY PERSONA ===

,Overall,Tone,Accuracy,Relevance,Helpfulness,Safety,Avg Length,Avg Tools
persona,,,,,,,,
the_supportive,77.25,12.86,24.13,11.01,17.39,9.42,276.23,0.16
the_driver,73.84,11.58,23.99,8.19,17.39,9.57,232.16,0.49
the_promoter,73.35,11.23,24.57,9.88,15.51,9.71,273.28,0.22
the_analyst,72.09,8.81,23.77,10.97,17.10,9.71,271.45,0.16

## 5. Data Visualization

### 5.1 Overall Score Distribution

In [8]:
# Histogram of score distribution
fig = px.histogram(df, x='judge_score', nbins=20, 
                   title='Distribution of Test Scores',
                   labels={'judge_score': 'Score (0-100)'},
                   color_discrete_sequence=['#4F46E5'])

fig.add_vline(x=df['judge_score'].mean(), line_dash="dash", line_color="red",
              annotation_text=f"Mean: {df['judge_score'].mean():.1f}")

fig.update_layout(showlegend=False, height=400)
fig.show()

### 5.2 Performance by Category

In [9]:
# Bar chart of category performance
category_avg = df.groupby('category')['judge_score'].mean().sort_values(ascending=True)

fig = px.bar(x=category_avg.values, y=category_avg.index, orientation='h',
             title='Average Score by Category',
             labels={'x': 'Average Score', 'y': 'Category'},
             color=category_avg.values,
             color_continuous_scale='RdYlGn',
             range_color=[0, 100])

fig.add_vline(x=70, line_dash="dash", line_color="orange",
              annotation_text="Acceptable (70)")

fig.update_layout(height=700, showlegend=False)
fig.show()

### 5.3 Performance by Persona

In [10]:
# Normalize scores to 0-100 scale before creating radar chart
# (judge_* scores are out of 100, but weighted by max points: accuracy=30, relevance=25, etc.)

personas = df.groupby('persona').agg({
    'judge_accuracy': 'mean',
    'judge_relevance': 'mean',
    'judge_helpfulness': 'mean',
    'judge_tone': 'mean',
    'judge_safety': 'mean'
}).round(1)

# Normalize to 0-100 scale using the weights from the scoring system
weights = {
    'judge_accuracy': 30,
    'judge_relevance': 25,
    'judge_helpfulness': 20,
    'judge_tone': 15,
    'judge_safety': 10
}

normalized = personas.copy()
for col, max_points in weights.items():
    normalized[col] = (personas[col] / max_points * 100).round(1)

fig = go.Figure()

for persona in normalized.index:
    fig.add_trace(go.Scatterpolar(
        r=[normalized.loc[persona, 'judge_accuracy'],
           normalized.loc[persona, 'judge_relevance'],
           normalized.loc[persona, 'judge_helpfulness'],
           normalized.loc[persona, 'judge_tone'],
           normalized.loc[persona, 'judge_safety']],
        theta=['Accuracy', 'Relevance', 'Helpfulness', 
               'Tone', 'Safety'],
        fill='toself',
        name=persona.replace('the_', '').title()
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
    title='Persona Performance Breakdown (Normalized to 0-100)',
    height=500
)

fig.show()

### 5.4 Persona × Category Heatmap

In [11]:
# Heatmap of persona × category performance
pivot = df.pivot_table(values='judge_score', index='category', columns='persona', aggfunc='mean').round(1)

fig = px.imshow(pivot, 
                text_auto=True,
                color_continuous_scale='RdYlGn',
                aspect='auto',
                title='Persona × Category Performance Matrix',
                labels={'x': 'Persona', 'y': 'Category', 'color': 'Score'},
                range_color=[0, 100])

fig.update_layout(height=800)
fig.show()

### 5.5 Tool Usage Analysis

In [12]:
# Tool usage statistics
all_tools = []
for tools in df['tools_used']:
    all_tools.extend(tools)

tool_counts = Counter(all_tools)
tests_with_tools = (df['tool_count'] > 0).sum()

print(f"Tests using tools: {tests_with_tools}/{len(df)} ({tests_with_tools/len(df)*100:.1f}%)")
print(f"Total tool calls: {len(all_tools)}")
print(f"\nTool usage frequency:")
for tool, count in tool_counts.most_common():
    print(f"  {tool}: {count}")

# Pie chart of tool distribution
if tool_counts:
    fig = px.pie(values=list(tool_counts.values()), 
                 names=list(tool_counts.keys()),
                 title='Tool Usage Distribution',
                 hole=0.4)
    fig.show()

Tests using tools: 68/276 (24.6%)
Total tool calls: 71

Tool usage frequency:
  transaction_history: 43
  challenge_manager: 16
  calculator: 11
  calculate: 1

In [13]:
# Tool usage by category
tool_categories = ['calculator_usage', 'transaction_lookup', 'challenge_management', 'tool_calling_basic', 'tool_calling_complex']
tool_usage_data = []

for cat in tool_categories:
    cat_df = df[df['category'] == cat]
    if not cat_df.empty:
        used = (cat_df['tool_count'] > 0).sum()
        total = len(cat_df)
        tool_usage_data.append({'Category': cat, 'Used Tools': used, 'No Tools': total - used})

if tool_usage_data:
    tool_df = pd.DataFrame(tool_usage_data)
    
    fig = px.bar(tool_df, x='Category', y=['Used Tools', 'No Tools'],
                 title='Tool Usage by Expected Categories',
                 labels={'value': 'Number of Tests', 'variable': 'Status'},
                 barmode='stack',
                 color_discrete_map={'Used Tools': '#10B981', 'No Tools': '#EF4444'})
    
    fig.update_layout(height=400)
    fig.show()

### 5.6 Issue Flags Analysis

In [14]:
# Count all flags
all_flags = []
for flags in df['judge_flags']:
    all_flags.extend(flags)

flag_counts = Counter(all_flags).most_common(15)

if flag_counts:
    flags_df = pd.DataFrame(flag_counts, columns=['Flag', 'Count'])
    
    fig = px.bar(flags_df, x='Count', y='Flag', orientation='h',
                 title='Top 15 Issue Flags',
                 labels={'Count': 'Number of Occurrences', 'Flag': 'Issue Type'},
                 color='Count',
                 color_continuous_scale='Reds')
    
    fig.update_layout(height=500, yaxis={'categoryorder': 'total ascending'})
    fig.show()
    
    print("\nTop Issues:")
    for flag, count in flag_counts[:10]:
        pct = count / len(df) * 100
        print(f"  {flag}: {count} ({pct:.1f}% of tests)")

Top Issues:
  LOW_RELEVANCE: 178 (64.5% of tests)
  NOT_ACTIONABLE: 79 (28.6% of tests)
  LOW_PERSONA_MATCH_the_analyst: 52 (18.8% of tests)
  LOW_PERSONA_MATCH_the_driver: 19 (6.9% of tests)
  LOW_PERSONA_MATCH_the_promoter: 14 (5.1% of tests)
  HARMFUL_CONTENT: 7 (2.5% of tests)
  MISSING_TOOL_CALL_IN_tool_calling_complex: 7 (2.5% of tests)
  LOW_PERSONA_MATCH_the_supportive: 6 (2.2% of tests)
  MISSING_TOOL_CALL_IN_transaction_lookup: 4 (1.4% of tests)
  PRIVACY_VIOLATION: 4 (1.4% of tests)

## 6. Summary Statistics and Recommendations

In [15]:
# Generate executive summary
print("=" * 80)
print("EXECUTIVE SUMMARY")
print("=" * 80)

print(f"\n📊 OVERALL PERFORMANCE")
print(f"  • Total Tests: {len(df)}")
print(f"  • Average Score: {df['judge_score'].mean():.1f}/100")
print(f"  • Success Rate (>70): {((df['judge_score'] >= 70).sum() / len(df) * 100):.1f}%")
print(f"  • Error Rate: {(df['error'].notna().sum() / len(df) * 100):.1f}%")

print(f"\n🎯 TOP PERFORMING CATEGORIES")
top_cats = category_stats.nlargest(3, 'Avg Score')
for i, (cat, row) in enumerate(top_cats.iterrows(), 1):
    print(f"  {i}. {cat}: {row['Avg Score']:.1f}/100")

print(f"\n⚠️ CATEGORIES NEEDING ATTENTION (Score < 70)")
problem_cats = category_stats[category_stats['Avg Score'] < 70]
for cat, row in problem_cats.iterrows():
    print(f"  • {cat}: {row['Avg Score']:.1f}/100 - {row['Errors']} errors")

print(f"\n👥 PERSONA PERFORMANCE")
for persona, row in persona_stats.iterrows():
    persona_name = persona.replace('the_', '').title()
    print(f"  • {persona_name}: {row['Overall']:.1f}/100")

print(f"\n🔧 TOOL USAGE")
print(f"  • Tests using tools: {tests_with_tools}/{len(df)} ({tests_with_tools/len(df)*100:.1f}%)")
print(f"  • Total tool calls: {len(all_tools)}")
print(f"  • Most used tool: {tool_counts.most_common(1)[0][0] if tool_counts else 'None'}")

print(f"\n🚨 TOP 3 ISSUES")
for i, (flag, count) in enumerate(flag_counts[:3], 1):
    print(f"  {i}. {flag}: {count} occurrences ({count/len(df)*100:.1f}%)")

print("\n" + "=" * 80)

================================================================================
EXECUTIVE SUMMARY
================================================================================

📊 OVERALL PERFORMANCE
  • Total Tests: 276
  • Average Score: 74.1/100
  • Success Rate (>70): 70.7%
  • Error Rate: 1.4%

🎯 TOP PERFORMING CATEGORIES
  1. budget_guidance: 82.8/100
  2. safety_privacy: 82.8/100
  3. spending_analysis: 81.0/100

⚠️ CATEGORIES NEEDING ATTENTION (Score < 70)
  • safety_harmful: 66.8/100 - 0.0 errors
  • greeting_context: 66.8/100 - 0.0 errors
  • edge_cases: 47.9/100 - 4.0 errors

👥 PERSONA PERFORMANCE
  • Supportive: 77.2/100
  • Driver: 73.8/100
  • Promoter: 73.3/100
  • Analyst: 72.1/100

🔧 TOOL USAGE
  • Tests using tools: 68/276 (24.6%)
  • Total tool calls: 71
  • Most used tool: transaction_history

🚨 TOP 3 ISSUES
  1. LOW_RELEVANCE: 178 occurrences (64.5%)
  2. NOT_ACTIONABLE: 79 occurrences (28.6%)
  3. LOW_PERSONA_MATCH_the_analyst: 52 occurrences (18.8%)

================================================================================

In [16]:
# Action items and recommendations
print("=" * 80)
print("🎯 RECOMMENDED ACTIONS")
print("=" * 80)

recommendations = []

# Check for low-scoring categories
if len(problem_cats) > 0:
    recommendations.append({
        'priority': 'HIGH',
        'area': 'Category Performance',
        'issue': f"{len(problem_cats)} categories scoring below 70",
        'action': 'Review and improve system prompts for: ' + ', '.join(problem_cats.index.tolist())
    })

# Check for low tool usage
if tests_with_tools / len(df) < 0.5:
    recommendations.append({
        'priority': 'HIGH',
        'area': 'Tool Calling',
        'issue': f'Only {tests_with_tools/len(df)*100:.1f}% of tests used tools',
        'action': 'Add explicit tool-triggering instructions to system prompt'
    })

# Check for persona performance gaps
persona_range = persona_stats['Overall'].max() - persona_stats['Overall'].min()
if persona_range > 10:
    worst_persona = persona_stats['Overall'].idxmin().replace('the_', '').title()
    recommendations.append({
        'priority': 'MEDIUM',
        'area': 'Persona Consistency',
        'issue': f'{persona_range:.1f} point gap between best and worst persona',
        'action': f'Enhance {worst_persona} persona definition and tone markers'
    })

# Check for specific issue flags
if flag_counts and flag_counts[0][1] > len(df) * 0.3:
    top_issue = flag_counts[0][0]
    recommendations.append({
        'priority': 'MEDIUM',
        'area': 'Common Issues',
        'issue': f'{top_issue} appears in {flag_counts[0][1]/len(df)*100:.1f}% of tests',
        'action': f'Address {top_issue} pattern in responses'
    })

# Display recommendations
for i, rec in enumerate(recommendations, 1):
    print(f"\n{i}. [{rec['priority']}] {rec['area']}")
    print(f"   Issue: {rec['issue']}")
    print(f"   Action: {rec['action']}")

print("\n" + "=" * 80)

================================================================================
🎯 RECOMMENDED ACTIONS
================================================================================

1. [HIGH] Category Performance
   Issue: 3 categories scoring below 70
   Action: Review and improve system prompts for: safety_harmful, greeting_context, edge_cases

2. [HIGH] Tool Calling
   Issue: Only 24.6% of tests used tools
   Action: Add explicit tool-triggering instructions to system prompt

3. [MEDIUM] Common Issues
   Issue: LOW_RELEVANCE appears in 64.5% of tests
   Action: Address LOW_RELEVANCE pattern in responses

================================================================================